### ISSUE TITLE
Rue absente dans l'export bano-63

### ISSUE THREAD

**Issue by NicolasDumoulin** [osm-fr/bano-data#10]
Bonjour,

Je ne retrouve pas la rue Serge Gainsbourg à Clermont-Ferrand (63113) dans l'export bano-63.csv. La rue est pourtant bien trouvée dans Fantoir et dans OSM :
http://cadastre.openstreetmap.fr/fantoir/#insee=63113&tab=3
http://tile.openstreetmap.fr/~cquest/leaflet/bano.html#19/45.78848/3.10012

**Comment by NicolasDumoulin** [comment]
Ok, c'est normal car il n'y a pas de numéro d'adresse sur cette rue.

**Comment by vdct** [comment]
....mériterait de rester ouvert pour l'instant car je ne vois pas de justification à ce que la rue soit absente de l'export.

**Comment by NicolasDumoulin** [comment]
Alors une question : y a-t-il d'autres rues dans les fichiers BANO ? Je veux dire une rue, pas un numéro.

**Comment by vdct** [comment]
En théorie il y a une ligne par numero d'adresse et une ligne par rue (avec l'équivalent du point turquoise) dans les fichiers en sortie. Mais je ne sais pas si ça répond à ta question ?

**Comment by NicolasDumoulin** [comment]
En théorie, soit.
En pratique, en regardant avec mes yeux (sans script exhaustif) je ne vois que des numéros dans full.csv.

**Comment by vdct** [comment]
Ok. Y'a clairement un truc à fixer, alors. À suivre ici.

**Comment by NicolasDumoulin** [comment]
Les fichiers contenant les numéro d'adresse ne sont pas destinés à contenir les rues seules.
cf. https://twitter.com/cq94/status/705308727478460417
