### ISSUE TITLE
Export des noms de rue

### ISSUE THREAD

**Issue by NicolasDumoulin** [osm-fr/bano-data#11]
Les exports actuels ne contiennent que les numéros d'adresses. Est-ce que BANO pourrait produire les exports des rues, sans numéro, avec uniquement les noms des rues de BANO ?
Ce ticket fait suite au ticket #10

**Comment by cquest** [comment]
L'export JSON contient ces informations car chaque voie ou lieu-dit correspond à une ligne du json, avec une latitude/longitude moyenne pour la voie ou le lieu-dit et aussi la liste des numéros avec leur position.

**Comment by NicolasDumoulin** [comment]
Ha d'accord. Au temps pour moi !
Tout est dans le JSON ! Merci
