### ISSUE TITLE
Is it abandoned?

### ISSUE THREAD

**Issue by dadoonet** [osm-fr/bano-data#12]
Hey

Looks like the repo has not been updated for a year now.

Is it expected?

Should this repo be closed now and should the mention on this page: https://www.data.gouv.fr/fr/datasets/base-d-adresses-nationale-ouverte-bano/ be removed?

**Comment by cquest** [comment]
We stopped this experimental publishing channel.

BANO data are available at: http://bano.openstreetmap.fr/data/

It is a daily update (except during maintenance).

**Comment by dadoonet** [comment]
Sure. I saw it and use it. Was just wondering if it should be obvious in the README and on the page I linked.

But thanks.
