### ISSUE TITLE
mauvaise priorisation des sources ?

### ISSUE THREAD

**Issue by nlehuby** [osm-fr/bano-data#8]
J'ai une adresse qui est 
- ok dans le jeu opendata
- ko dans le cadastre
- pas présente dans OSM
- (et ok dans la BAN)

Dans les données BANO, c'est l'adresse du cadastre qui est retenue : 
![charlemagne](https://cloud.githubusercontent.com/assets/919962/12063413/7dfe99cc-afae-11e5-8918-a5596535e815.png)
93 Cours Charlemagne, à Lyon
http://tile.openstreetmap.fr/~cquest/leaflet/bano.html#20/45.73571/4.81699

**Comment by vdct** [comment]
Côté BANO on n'a pas cette adresse dans le jeu de données OpenData. On n'a que la source Cadastre, c'est donc elle qui sort.
Donc à la fois : 
- on n'est potentiellement pas à jour sur la source OD. As-tu un lien vers celle où l'adresse est ok ?
- si tu sais situer le bon positionnement de l'adresse sur le terrain, la saisir dans OSM règlera le problème au prochain export, OSM étant prioritaire sur aussi bien l'OD que le Cadastre
